### ISSUE TITLE
User Story : Contact section to send a message to the band

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-pp5#10]
As a potential collaborator or event organizer, I want to access the Contact section to send a message to the band or inquire about booking them for a gig, ensuring that contact information is SEO-optimized

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [x] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Create Models</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Create Views</label>
- [x] <label><input type="checkbox" disabled /> Task 3 :  Render Templates</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Test Local</label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Test Heroku</label>
