### ISSUE TITLE
User Story : Administrator access for power users

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-pp5#12]
As an administrator, I want a secure login system to manage the website's content and make updates to the band's information.

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [x] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Create Models</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Register Models</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Create super user</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 : Access in render template</label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 : Access in Heroku </label>
