### ISSUE TITLE
User Story : (SEO) Make Site Optimized for Search Engines

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-pp5#13]
As a fan, I want the website to be optimized for search engines to improve its visibility and ranking in search results, helping more people discover the band's music and content.

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [x] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : ###############</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : ###############</label>
- [x] <label><input type="checkbox" disabled /> Task 3 : ###############</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  ############## </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  ############## </label>
