### ISSUE TITLE
User Story : Newsletter to receive regular updates and news about the band

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-pp5#14]
As a fan, I want to sign up for a newsletter to receive regular updates and news about the band, and the newsletter signup process should be optimized for SEO.

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [x] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Create Models</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Create Views</label>
- [x] <label><input type="checkbox" disabled /> Task 3 : Render Templates</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Check Local </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Check Heroku </label>
