### ISSUE TITLE
User Story :  User registration and login 

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-pp5#16]
As a "###" I want  to "###" so that I "###"

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [x] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Initial Setup </label>
- [x] <label><input type="checkbox" /> Task 2 : Creating the Register View </label>
- [x] <label><input type="checkbox" /> Task 3 : Registration Form with Additional Fields </label>
- [x] <label><input type="checkbox" /> Task 4 : Log in and Log out </label>
- [x] <label><input type="checkbox" /> Task 5 : Customizing Templates </label>
- [x] <label><input type="checkbox" /> Task 6 : Creating an Admin User </label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Check On Local</label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Test On Heroku </label>
