### ISSUE TITLE
User Story :  Create checkout system using stripe

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-pp5#17]
As  user I want  to be able to make a purchase so that I can listen to the bands music and wear the clothes. 

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [x] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Install and configure Stripe</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Enable handlers </label>
- [x] <label><input type="checkbox" disabled /> Task 3 : Create purchase mechanism</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Test purchase on local site </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Test purchase in Heroku </label>
