### ISSUE TITLE
User Story : Create user profiles form and database

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-pp5#18]
As a fan I want  to login and save my personal info so that I can receive recipes of purchase

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [x] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Create profiles app</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Create form and view</label>
- [x] <label><input type="checkbox" disabled /> Task 3 : Create template</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Test Local </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Test Heroku </label>
