### ISSUE TITLE
User Story :  Bug No Image not rendering

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-pp5#19]
As a "###" I want  to "###" so that I "###"

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Search for Error</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Include bug fix</label>
- [x] <label><input type="checkbox" disabled /> Task 3 :  Render to Template</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 : Test Local </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Test Heroku </label>
