### ISSUE TITLE
User Story : Clear and Concise Status Messages for all necessary Events

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-pp5#2]
As a user, I want to receive clear status messages so that I can stay informed about my any issues.

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [x] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Edit Settings.py</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Add JavaScript timer</label>
- [x] <label><input type="checkbox" disabled /> Task 3 : Confirm function</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Messages appear after login/logout on site</label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Messages appear after login/logout on site (Heroku) </label>
