### ISSUE TITLE
User Story : Navigation

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-pp5#4]
As a returning visitor, I want to see a navigation menu that allows me to easily switch between different sections of the website

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [x] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Create HTML template</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Create Views and Urls </label>
- [x] <label><input type="checkbox" disabled /> Task 3 : Render Home Page With Nav Bar </label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Templates Render In Vscode</label>
- [x] <label><input type="checkbox" disabled /> Criteria 2 :  Templates Render in Heroku</label>
- [x] <label><input type="checkbox" disabled /> Criteria 3 :  All links render successfully in both</label>
