### ISSUE TITLE
User Story : Band's social media profiles

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-pp5#5]
As a fan who enjoys social media, I want the website to have links to the band's social media profiles for easy access to their updates and posts.

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [x] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Create Facebook</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Create Band Profile</label>
- [x] <label><input type="checkbox" disabled /> Task 3 : Link Facebook to Project</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Test Local </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Test Heroku </label>
