### ISSUE TITLE
User Story : Accessibility needs

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-pp5#6]
As a user with accessibility needs, I expect the website to be designed with accessibility features and provide alternative text for images and readable content.

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [x] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Aria Check</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Symantec Cheek</label>
- [x] <label><input type="checkbox" disabled /> Task 3 : Wave Test</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Check Local </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Check Heroku </label>
