### ISSUE TITLE
User Story : Optimized for search engines (SEO)

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-pp5#7]
As a fan who wants to stay informed, I want to easily find a section that provides the latest news and updates from the band while ensuring that the website is optimized for search engines (SEO).

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [x] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Meta Tags Search</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Sitemap XML</label>
- [x] <label><input type="checkbox" disabled /> Task 3 : Robots text file </label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Test Local</label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Test Remote </label>
