### ISSUE TITLE
User Story :  Music section to listen to the band's latest tracks

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-pp5#8]
As a music enthusiast, I want to navigate to the Music section to listen to the band's latest tracks

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [x] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Create Models</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Create Views </label>
- [x] <label><input type="checkbox" disabled /> Task 3 : Render Templates</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Renders on Local</label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Renders on Heroku </label>
