### ISSUE TITLE
User Story : Store section to purchase band merchandise and CD

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-pp5#9]
As a  fan, I want to explore the Store section to purchase band merchandise, such as t-shirts, posters, and CDs, to show my support, and I want product listings to be SEO-friendly

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [x] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Create "Merchandise" app</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Populate database with data</label>
- [x] <label><input type="checkbox" disabled /> Task 3 : Render all items in template</label>
- [x] <label><input type="checkbox" disabled /> Task 4 : Render single item template</label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  All items and single item render in template </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  All items and single item render in template in Heroku</label>
